---
AWSTemplateFormatVersion: 2010-09-09
Description: 'SPECIAL RESOURCES. DO NOT TOUCH. This StackSet will enable AWS CloudTrail.'

Resources:
  TrailLogGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties: 
      LogGroupName: !Sub '/aws/cloudtrail/default-cloudtrail-${AWS::AccountId}'

  TrailKMS:
    Type: 'AWS::KMS::Key'
    Properties:
      Description: 'CMK for encryption and decryption of default-cloudtrail logs.'
      Enabled: True
      EnableKeyRotation: True
      Tags:
        - Key: 'Name'
          Value: !Sub 'alias/default-cloudtrail-${AWS::AccountId}'
        - Key: 'Environment'
          Value: 'special'
        - Key: 'Description'
          Value: 'CMK for encryption and decryption of default-cloudtrail logs.'
      KeyPolicy: 
        Version: '2012-10-17'
        Statement: 
          - Sid: 'AllowCloudTrailToDescribeKey'
            Effect: 'Allow'
            Principal: 
              Service: 
                - 'cloudtrail.amazonaws.com'
            Action: 
              - 'kms:DescribeKey'
            Resource: '*'
          - Sid: 'AllowCloudTrailToGenerateDataKeys'
            Effect: 'Allow'
            Principal: 
              Service: 
                - 'cloudtrail.amazonaws.com'
            Action: 
              - 'kms:GenerateDataKey*'
            Resource: '*'
            Condition:
              StringLike:
                kms:EncryptionContext:aws:cloudtrail:arn: !Sub 'arn:aws:cloudtrail:*:${AWS::AccountId}:trail/*'
          - Sid: 'EnableIAMUserPermissions'
            Effect: 'Allow'
            Principal: 
              AWS: 
                - !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 
              - 'kms:*'
            Resource: '*'

  TrailKMSAlias:
    Type: 'AWS::KMS::Alias'
    Properties:
      AliasName: !Sub 'alias/default-cloudtrail-${AWS::AccountId}'
      TargetKeyId: !Ref TrailKMS

  Trail:
    Type: 'AWS::CloudTrail::Trail'
    Properties:
      TrailName: !Sub 'default-cloudtrail-${AWS::AccountId}'
      S3BucketName: !Sub 'default-cloudtrail-ap-southeast-1-${AWS::AccountId}'
      CloudWatchLogsLogGroupArn: !GetAtt 
        - TrailLogGroup
        - Arn
      CloudWatchLogsRoleArn: !Sub 'arn:aws:iam::${AWS::AccountId}:role/service-role/cloudtrail.amazonaws.com/ServiceRoleForCloudtrail_default-cloudtrail'
      KMSKeyId: !Ref TrailKMS
      IsLogging: True
      EnableLogFileValidation: True
      IncludeGlobalServiceEvents: True
      IsMultiRegionTrail: True
      Tags:
        - Key: 'Name'
          Value: !Sub 'default-cloudtrail-${AWS::AccountId}'
        - Key: 'Environment'
          Value: 'special'
        - Key: 'Description'
          Value: 'Default Management Trail for All Regions'
