---
AWSTemplateFormatVersion: 2010-09-09
Description: 'SPECIAL RESOURCES. DO NOT TOUCH. This StackSet will create several IAM Roles for scaffolding resources.'

Resources:
  TrailRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: 'ServiceRoleForCloudtrail_default-cloudtrail'
      Path: '/service-role/cloudtrail.amazonaws.com/'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: 'Allow'
            Principal:
              Service:
                - 'cloudtrail.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: 'AllowCloudtrailLogDeliveryToCloudwatchLogs'
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'logs:PutLogEvents'
                  - 'logs:CreateLogStream'
                Resource: !Sub 'arn:aws:logs:ap-southeast-1:${AWS::AccountId}:log-group:/aws/cloudtrail/default-cloudtrail-${AWS::AccountId}*'

  ConfigRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: 'ServiceRoleForConfig_default-config'
      Path: '/service-role/config.amazonaws.com/'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - config.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSConfigRole

  CloudConformityMonitoringRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: 'ServiceRoleForLambda_default-cloudconformity-monitoring'
      Path: '/service-role/lambda.amazonaws.com/'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: 'Allow'
          Principal:
            Service:
            - 'lambda.amazonaws.com'
          Action:
          - 'sts:AssumeRole'
      Policies:
      - PolicyName: 'AllowCloudConformityMonitoringToCreateAndPutLogs'
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: 'Allow'
            Action:
            - 'logs:CreateLogGroup'
            Resource: !Sub 'arn:aws:logs:*:${AWS::AccountId}:*'
          - Effect: 'Allow'
            Action:
            - 'logs:CreateLogStream'
            - 'logs:PutLogEvents'
            - 'logs:DescribeLogStream'
            Resource: !Sub 'arn:aws:logs:*:${AWS::AccountId}:log-group:/aws/lambda/CloudConformityMonitoring*'

Outputs:
  TrailRoleARN:
    Description: 'The ARN of the role for AWS CloudTrail.'
    Value: !GetAtt
      - TrailRole
      - Arn
    Export:
      Name: 'default-trail-role'


  ConfigRecorderRoleARN:
    Description: 'The ARN of the role for AWS Config.'
    Value: !GetAtt
      - ConfigRole
      - Arn
    Export:
      Name: 'default-config-role'

  CloudConformityMonitoringRoleARN:
    Description: 'The ARN of the role for CloudConformity Lambda.'
    Value: !GetAtt
      - CloudConformityMonitoringRole
      - Arn
    Export:
      Name: 'default-cloudconformity-monitoring-role'
